#!/usr/bin/python3
#Exception Handling 1st example #
import sys
def main():
randomlist = ['a',0,2]
for val in randomlist:
    try:
        print("The entry is entry",entry)
        r = 1/int(val)
        break
    except:
        print("OO")

if __name__ == "__main__":
    main()

